NebraLtd/hm-pyhelper

- .github/workflows/unit-tests.yml
- README.md
- hm_pyhelper/tests/utils/test_logger.py
- hm_pyhelper/utils/logger.py
- setup.py
**Why**
It is helpful to have verbose logs that are consistent across all services. 
**How**
This logger has been copied from [hm-config](https://github.com/NebraLtd/hm-config/blob/ca7b5e3e05041b9fdaaa238e3240c1f1e38f1cfd/gatewayconfig/logger.py).
> feat: add logger

- README.md
- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_get_region.py
- requirements.txt
- setup.py
**Why**
In the process of refactoring hm-pktfwd. It is not the best place for logic that spans multiple services.
**How**
Port logic from establishing a device's region from hm-pktfwd. Use retry library instead of `while` loops with `sleep`.
**References**
Related to: https://github.com/NebraLtd/hm-pktfwd/issues/45
> feat: get_region

- setup.py
**Why**
Must release to finish implementing [ECC fix](https://github.com/NebraLtd/hm-diag/issues/167).
**How**
Bump version
**References**
Related PR: https://github.com/NebraLtd/hm-pyhelper/pull/46/
> release: v0.8.13

- .bumpversion.cfg
- .github/workflows/publish-to-pypi-test.yml
- setup.py
**Why**
Duplicate versions prevent pushing the package live on TestPyPi as it doesn't overwrite the previous package.
**How**
Using Bump2Version will automatically bump up the minor version and do a commit with new git tags. 
Github Action New Steps:
- Install Bump2Version
- Run Bump2Version to update the version in setup.py and .bumpversion.cfg
- Bump2Version creates a git tag and commits the files
- Using ad-m/push action I push the latest commit
> Implemented bump2version action

- .github/workflows/publish-to-pypi-test.yml
**Why**
Version bump is happening on any branch, this means any push on a subbranch when testing will result in the version incrementing and might result in merge conflicts and also different versions across the whole project
**How**
Added a master branch if check to each job involving bumping the version and publishing the package, this should now avoid bumping the version on any sub-branch and rely on the master branch
> Version bump should only happen on master

- hm_pyhelper/diagnostics/__init__.py
- hm_pyhelper/diagnostics/diagnostic.py
- hm_pyhelper/diagnostics/diagnostics_report.py
- hm_pyhelper/exceptions.py
- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_diagnostic_report.py
**Why**
Instead of operating on raw Python `dict`s to communicate diagnostics state, we should use an abstraction with an API that makes it clear how to interact with. For example, we don't want failed diagnostics to throw an exception, but instead write information to the corresponding key of the diagnostic output.
**How**
Introduced Diagnostic and DiagnosticsReport classes to be used by hm-diag and hm-pyhelper.
Also changes the error signaling of `get_gateway_mfr_test_result` so that it can be handled more cleanly in hm-diag.
**References**
- Related to: https://github.com/NebraLtd/hm-diag/issues/181
- Related to: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/9
- Related to: https://github.com/NebraLtd/hm-diag/issues/204
> feat: add Diagnostic and DiagnosticsReport

- README.md
- hm_pyhelper/lock_singleton.py
- hm_pyhelper/tests/test_lock_singleton.py
- setup.py
**Why**
Make lock_ecc() decorator forward the exception correctly.
**How**
- Distinguish the exception between the ECC_BUSY_ERROR and the internal exception that comes from the original method.
- Release the acquired lock when the internal exception occurs.
**References**
https://github.com/NebraLtd/hm-pyhelper/pull/46
> Make lock_ecc() decorator forward the exception correctly

- .bumpversion.cfg
- .github/workflows/publish-to-pypi-test.yml
- setup.py
**Why**
We are moving away from bump2version and implementing another solution from [here](https://github.com/NebraLtd/hm-pyhelper/issues/20)
**How**
Removed all references to bump2version in the git workflow
> Removed all references to bump2version

- hm_pyhelper/miner_param.py
- setup.py
**Why**
Support rockpi
**How**
`--path /dev/i2c-7` for rockpi needs to come before the command or it will fail
**References**
Relates-to: #67
Relates-to: https://github.com/NebraLtd/hm-diag/issues/237#issuecomment-974694244
> fix: correct order for extend commands

- hm_pyhelper/hardware_definitions.py
- hm_pyhelper/tests/test_hardware_definitions.py
**Issue**
- Link: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/12
- Summary: Support different FCC and ICC IDs on different devices.
**How**
- Added FCC and ICC ids to variant_defintions.
- Only set values for variants that are currently explicitly
handled in HPT: https://github.com/NebraLtd/Hotspot-Production-Tool/blob/d948acc4245cbe66777cae26660789b249cbb349/app/main.py#L90
- For future proofing, made FCC_IDS an array even though we currently only seem to have one
value per device type.
**References**
- Related to: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/34
- Related to: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/11
- Related to: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/10
**Checklist**
> feat(hardware definitons): add FCC and IC fields

- README.md
- hm_pyhelper/exceptions.py
- hm_pyhelper/hardware_definitions.py
- hm_pyhelper/tests/test_hardware_definitions.py
- setup.py
**Issue**
- Link: https://github.com/NebraLtd/Hotspot-Production-Tool/issues/12
- Summary: Creating a helper so that HPT can easily access FCC and IC IDs.
**How**
Helper method added to hardware_definitions
**Checklist**
> feat(hardware definitions): helper to get attrs

- hm_pyhelper/hardware_definitions.py
- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_hardware_definitions.py
- hm_pyhelper/tests/test_miner_param.py
- setup.py
**Issue**
Summary: The library currently uses a Balena environment variable to determine the device type and choose ECC device for gateway_mfr in the case of RockPI.  It also does not provide a mechanism to support other hardware platforms where the ECC device is not /dev/i2c-1.  Besides this method making the system depend on Balena, it is also incoherent with the objective of defining hardware specific attributes in the library itself.
**How**
- Added a new attribute "ECCBUS" and modified run_gateway_mfr() to use this attribute instead of is_rockpi().
- Modified the hardware definitions to include the new attribute.
**References**
#69 
**Checklist**
> Add ECCBUS attribute and use it for gateway_mfr

- hm_pyhelper/diagnostics/diagnostics_report.py
- hm_pyhelper/tests/test_diagnostic_report.py
- setup.py
Related to https://github.com/NebraLtd/Hotspot-Production-Tool/issues/55
Moved logic of did_miner_pass_diagnostics from Miner class in HPT to
DiagnosticsReport.passed method. Added relevant test cases.
**Issue**
Avoid code duplication and use better logic for determining if diagnostics have passed.
- Link:
- Summary:
Previously only the passed key was being checked to see if diagnostics report had passed. Now this checks more keys to make sure all keys required for passing the report at manufacturing have valid values.
**How**
Implementation logic from https://github.com/NebraLtd/Hotspot-Production-Tool/blob/kashifpk/refactoring/app/src/hpt/miner.py#L165 was taken and moved to `DiagnosticReport.passed` method with appropriate adjustments.
**Checklist**
> Better logic for DiagnosticsReport.passed method

- hm_pyhelper/diagnostics/diagnostics_report.py
- hm_pyhelper/tests/test_diagnostic_report.py
- setup.py
**Issue**
Proper method of setting errors for diagnostics report (used in hm-diag) was using old style keys.
**How**
Added support in `DiagnosticsReport.record_failure` method to add both provided key and friendly_key to errors.
**Checklist**
> Diagnostics report friendly keys support

- hm_pyhelper/diagnostics/diagnostics_report.py
- hm_pyhelper/tests/test_diagnostic_report.py
- setup.py
**Issue**
- Link: https://github.com/NebraLtd/Hotspot-Production-Tool/pull/117
- Summary: Add helper method to be used by l[abel printing logic](https://github.com/NebraLtd/Hotspot-Production-Tool/pull/117#discussion_r782612628) in HPT to validate before printing.
**How**
Added method to DiagnosticsReport to detect which keys are present.
**References**
**Checklist**
> feat(diagnostics): get_missing_keys

- hm_pyhelper/miner_json_rpc/client.py
- hm_pyhelper/tests/test_miner_json_rpc.py
- requirements.txt
- setup.py
**How**
Remove jsonrpcclient library from source code. And start using 'requests' library for all requests.
**Checklist**
> Remove library jsonrpcclient from hm_pyhelper 

- hm_pyhelper/miner_json_rpc/client.py
- hm_pyhelper/tests/test_miner_json_rpc.py
- setup.py
**How**
When trying to get information using the request "peer_book". It always returns None.
It is necessary to add the ability to added the payload for some requests for correct operation.
> Fix get peer book requests

- setup.py
**Issue**
- Link: Follow up to: https://github.com/NebraLtd/hm-pyhelper/pull/99
- Summary: Dependencies currently need to be added to requirements.txt and setup.py
**How**
So that they will be included when pyhelper imported
into another project. Also removed jsonrpcclient
which is no longer being used.
**References**
**Checklist**
> fix: added dependencies to setup.py

- setup.cfg
Since this is just a config change no need to bump version for this one as it will only effect devs.
> Increased max line length to 100 for flake8

- hm_pyhelper/hardware_definitions.py
- setup.py
**Issue**
(NebraLtd/hm-pyhelper#125)
- Summary:
The RAK button has been incorrectly mapped to GPIO21 and we needed to move it to GPIO7 for the actual hardware (RAK2287 Pi HAT). It will also require a change in the config.txt but this will be done in another repo later.
**How**
- The GPIO has been set to 7 for COMP-RAKHM
**Checklist**
> Fixed: RAK button GPIO mapping has been corrected.

- hm_pyhelper/util/pgp.py
- setup.py
`util.get_payload_from_clearsigned_message` was not extracting payload correctly if the original payload file used for signing did not end with a new line. This fixes it.
> Bugfix for get payload from clearsigned message

- hm_pyhelper/tests/test_util_pgp.py
- hm_pyhelper/util/pgp.py
Added regression for payload with no newline at the end to existing test case.
> get payload from clearsigned message test update

- hm_pyhelper/hardware_definitions.py
- hm_pyhelper/sbc.py
- hm_pyhelper/tests/test_hardware_definitions.py
- setup.py
* read model information from /proc/device-tree/model
in the absense of balena env variable
**fix: is_rockpi and is_raspberry_pi should not break outside Balena**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/69
- Summary:
**How**
We read /proc/device-tree/model in the absence of BALENA_DEVICE_TYPE to determine device type.
**References**
**Checklist**
> fix: is_rockpi and is_raspberry_pi should not break outside Balena #69

- hm_pyhelper/hardware_definitions.py
- hm_pyhelper/sbc.py
- setup.py
**#153**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/153
- Summary: support sbc types pi zero 1 and 2
**How**
added balena device types names
fixed spidev number for pi zero
**References**
**Checklist**
>  add support for balena device types pi zero #153 

- hm_pyhelper/hardware_definitions.py
This reverts commit 40a07c9301f665648cd09d2ab9154a4e4a25ff5c.
**[Issue](https://github.com/NebraLtd/hm-pyhelper/issues/153)**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/153
- Summary: had merged wrong spi dev to master. reverting.
**How**
Mistakenly I thought new carrier board for light gateway and old hat are same. Modified spidev to make old hat work with pi zero but that is not the case. New carrier board uses spi1 for concentrator.
**References**
**Checklist**
> Revert "fix: pi zero support, spi dev number #153"

- setup.py
* bump pyhelper version to 0.13.21
**#153**
- Link:
- Summary:
**How**
**References**
**Checklist**
> fix: add support for balena device types pi zero and radxa-zero #153

- requirements.txt
- setup.py
**Issue**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/164
- Summary:
[packaging](https://pypi.org/project/packaging/) is used for gateway_mfr version checking, so `packaging` dependency needs to be added.
**How**
**References**
**Checklist**
> Add packaging dependency

- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_miner_param.py
- setup.py
**Issue**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/164
- Summary:
Subprocess output is byte array but not the string. It needs to be converted before handled as string.
**How**
`decode()` method should be called on the byte array in order to convert to string.
**References**
**Checklist**
> Fix parsing subprocess output

- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_logger.py
- setup.py
Added retry logic for ECC key provisioning and fixed a test case for testing the logger that was somehow broken as logging level by default is INFO and test was logging a DEBUG log message and expecting output in captured logs.
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> ECC key provisioning retry logic

- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_miner_param.py
- setup.py
**Issue**
- Fixed code for new gateway_mfr result format
- Updated test cases for the new gateway_mfr (>0.2.0) version response format.
- Fixed provisioning being passed as list bug
- Added key generation logic as backup if key provisioning fails.
- Link:
- Summary:
**How**
**References**
**Checklist**
> key generation backup logic and bugfix

- .github/workflows/publish-to-pypi-test.yml
- .github/workflows/publish-to-pypi.yml
Update gateway-mfr-rs to latest release v0.2.2
Ref https://github.com/helium/gateway-mfr-rs/releases/tag/v0.2.2
> gateway-mfr-rs: Update to latest release v0.2.2

- hm_pyhelper/hardware_definitions.py
- setup.py
add definition for pycom cm4
see #195 also
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: add pycom cm4

- hm_pyhelper/miner_param.py
- hm_pyhelper/tests/test_miner_param.py
- setup.py
**Issue**
- Link: https://github.com/NebraLtd/helium-syncrobit/issues/10
- Summary: remove unnecessary ECC lock and improve bus check
**How**
- ECC lock not required on this check because all we are doing is checking the i2c address of the attached device.
- persist a generated ECC location (from the i2c bus) to file to make get_ecc_location() function more efficient and to remove unnecessary calls to the i2c bus 
- additional tests for SWARM_KEY_URI_OVERRIDE and new "persist to file" feature
**References**
Ref: https://github.com/NebraLtd/helium-syncrobit/issues/10
Ref: https://github.com/NebraLtd/helium-syncrobit/issues/2
**Checklist**
> fix: remove unnecessary ECC lock and improve bus check

- requirements.txt
- setup.py
- test-requirements.txt
As this package creates a lot of long time build issues I've removed direct dependency from here to let parent app decide which grpcio version to use.
**Checklist**
> Removed grpcio direct requirement

- .github/workflows/publish-to-pypi-test.yml
**Issue**
The publish command in `publish-to-test-pypi` workflow is missing the `-r` argument to specify the test repo.
- Link:
- Summary:
**How**
**References**
**Checklist**
> Fix publish-to-test-pypi workflow

- .github/workflows/publish-to-pypi.yml
**Issue**
Poetry PyPI token needs to be configured using `pypi-token.pypi` instead of `http-basic.pypi`.
- Link:
- Summary:
**How**
**References**
**Checklist**
> Fix pypi publishing workflow

- hm_pyhelper/sbc.py
- pyproject.toml
Ref https://github.com/NebraLtd/hm-diag/issues/602 and https://github.com/NebraLtd/hm-diag/issues/606
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: move commercial fleet check to hm-pyhelper from diag
