NebraLtd/hm-pyhelper

.gitignore
setup.py

Add basic package files and create structure

init basic package files

---

.github/workflows/unit-tests.yml

Adds unit tests

---

README.md
hm_pyhelper/hardware_definitions.py
hm_pyhelper/tests/test_get_mac_address.py
setup.py

Closes https://github.com/NebraLtd/hm-pyhelper/issues/6. Merges in hardware definitions.

Merges in hardware definition

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
setup.py

Fixes path to gateway_mfr

---

hm_pyhelper/miner_param.py
setup.py

Closes https://github.com/NebraLtd/hm-pyhelper/issues/22
* Return `False` instead of `None` to make result JSON compatible

Tweaks MAC parsing

---

.bumpversion.cfg
hm_pyhelper/hardware_definitions.py
hm_pyhelper/miner_param.py
setup.py

* Introduces new helper functions to determine what hardware platform we're running on based on Balena's `BALENA_DEVICE_TYPE`
* Uses above check to user the right I2C bus when interacting with the ECC

Adds conditional checks for RockPi

---

setup.py

**Why**
Want to use https://github.com/NebraLtd/hm-pyhelper/pull/55

release: v0.11.1

---

setup.py

**Why**
Want to use: https://github.com/NebraLtd/hm-pyhelper/pull/54

release: v0.11.2

---

.bumpversion.cfg
hm_pyhelper/diagnostics/diagnostics_report.py
hm_pyhelper/tests/test_diagnostic_report.py
setup.py

**Why**
Bad logic was causing all initFile.txt calls to fail.
**How**
Was previously looking up obj attribute instead of
dict item/key.

fix: DiagnosticsReport#get_report_subset

---

hm_pyhelper/hardware_definitions.py
setup.py

**Why**
Add RockPi Outdoor version with cellular capability
**How**
Add to hardware definitions
**References**

feat: add RockPi Outdoor

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
- Link: https://github.com/NebraLtd/hm-config/issues/96
- Summary: support RockPi with button and led features
**How**
as we are moving to mraa in hm-config we will use physical pin definitions for button and status LEDs instead of the system pin numbers (as per https://wiki.radxa.com/Rockpi4/dev/libmraa )
N/A
**References**
Ref https://github.com/NebraLtd/hm-config/issues/96
Ref https://github.com/NebraLtd/hm-config/blob/2297842825bac09b9b0338681c2219b5338b1ea8/gatewayconfig/gatewayconfig_app.py#L90-L93
**Checklist**

fix: update button pin IDs

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml

Update gateway-mfr-rs to latest release v0.1.7
Ref https://github.com/helium/gateway-mfr-rs/releases/tag/v0.1.7
Also update checksum check to work properly

gateway-mfr-rs: Update to latest release v0.1.7

---

README.md

**Issue**
- Link: #43
- Summary: build gateway Mfr separately (this just adds more README info)
**How**
Add info about gateway-mfr-rs auto build
**References**
#43 
#78
**Checklist**

readme: add more info to README

---

hm_pyhelper/miner_json_rpc/client.py
hm_pyhelper/tests/test_miner_json_rpc.py
setup.py

**How**
After the last update. One request is not working properly. Need to fix this by removing invalid parameters.
**References**
[Error link](https://sentry.io/share/issue/70a2bf1b30be47cd8e61908290362831/)

Fix bug with request parametr in MinerClient class

---

setup.py

**Issue**
Bump package version

Bump setup verison package

---

hm_pyhelper/diagnostics/diagnostics_report.py
hm_pyhelper/tests/test_diagnostic_report.py
setup.py

Related to:
https://github.com/NebraLtd/Hotspot-Production-Tool/issues/122
Validate add gateway transaction if destination_name key is present
in diagnostics report.
**Checklist**

Add gateway transaction validation in diagnostics report.

---

hm_pyhelper/constants/diagnostics.py
hm_pyhelper/constants/shipping.py
setup.py

Initial implementation of constants package for stuff that gets used in multiple repos.
**Checklist**

Initial constants in the constants package.

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
- Link:
- Summary:
**How**
update rak gpio pin
**References**
**Checklist**

fix: update rak concentrator reset gpio pin

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
- Link: #114 
- Summary: fix sensecap button
**How**
correct sensecap button and LED gpio as per #114
**References**
#114 
**Checklist**

fix: correct sensecap button and LED

---

hm_pyhelper/tests/test_util_pgp.py
hm_pyhelper/util/pgp.py
setup.py

**Issue**
PGP helper code.
**Checklist**

Helper function to extract payload from PGP clearsigned message files.

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
- Link: #130 
- Summary: add pisces miner
**How**
Add pisces miner
**References**
Co-authored-by: radicale <radicale@users.noreply.github.com>
Relates-to: #130
**Checklist**

feat: add pisces p100 miner

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
- Link: N/A
- Summary: add Radxa Zero hardware
**How**
Add Radxa Zero light variant
Known issue: reset pin is correct for the light hotspot board but this pin on the Radxa Zero is an ADC so we will need to change this
**References**
https://wiki.radxa.com/Zero/hardware
https://wiki.radxa.com/Zero
**Checklist**

feat: add Radxa Zero

---

hm_pyhelper/hardware_definitions.py
setup.py

#149
**Issue**
- Link:
- Summary:
**How**
**References**
#150
#149
**Checklist**

fix: reset pin 13 / GPIO 503

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
#165 
- Summary:
Added hardware definition parameters for Cotx X3 hotspot
**How**
Took the multimeter, screwdriver and gone rouge with them :smile: 
**Checklist**

Added Cotx X3 hardware definition parameters

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
NebraLtd/hm-pyhelper#165
**Checklist**

Fixed Cotx X3 ECC I2C addr

---

hm_pyhelper/tests/data/sentry/sample_exception_event.json
hm_pyhelper/tests/data/sentry/sample_logging_event.json
hm_pyhelper/tests/data/sentry/sample_logging_hints.json
hm_pyhelper/tests/test_util_sentry.py
hm_pyhelper/util/sentry.py
setup.py

* added function to be used as before_send hook with sentry sdk
**[Issue](https://github.com/NebraLtd/hm-diag/issues/385)**
- Link: https://github.com/NebraLtd/hm-diag/issues/385
- Summary: add support for exponential suppression of error messages by using before_send sentry hook
**How**
**References**
**Checklist**

feat: Exponential sentry error suppression #385

---

setup.py

**Issue**
- Summary:
Fix typo in setup.py.
**How**
**References**
**Checklist**

Fix packaging dependency requirement

---

hm_pyhelper/miner_param.py
setup.py

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Removed provision key retry logic as that already happens at hm-diag's end

---

hm_pyhelper/miner_param.py
setup.py

Do not use forced key regeneration.

Revert key regeneration logic.

---

hm_pyhelper/miner_param.py
hm_pyhelper/tests/test_miner_param.py
setup.py

Regarding https://github.com/NebraLtd/product-management/issues/180
**Checklist**

Support for performing key provisioning on any slot and backup key generation logic.

---

hm_pyhelper/hardware_definitions.py
setup.py

Controllino is now also known as Conelcom
Closes: #198
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: add Conelcom name

---

hm_pyhelper/hardware_definitions.py
setup.py

update pycom reset gpio to 23
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

fix: update pycom reset gpio

---

hm_pyhelper/miner_param.py
setup.py

Fixes the typos identified by @gfelisberto in #145 
Relates-to: #145
Co-authored-by: Gustavo Felisberto <gustavo@felisberto.net>
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

fix: typos identified in PR 145

---

requirements.txt
setup.py
test-requirements.txt

**Issue**
- Link:
- Summary: update requirements.txt
**How**
- bump all to latest versions
**References**
**Checklist**

feat: update requirements.txt

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml

Update gateway-mfr-rs to latest release v0.3.2
Ref https://github.com/helium/gateway-mfr-rs/releases/tag/v0.3.2

gateway-mfr-rs: Update to latest release v0.3.2

---

.github/workflows/unit-tests.yml
setup.py
test-requirements.txt

Closes: #212
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: add pytest coverage

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
MANIFEST.in
hm_pyhelper/miner_param.py
setup.py

**Issue**
- Link: #215 
- Summary: gateway_mfr not working on aarch64 base images
**How**
- add aarch64 version
**References**
Closes: #215
**Checklist**

feat: add aarch64 version of gateway_mfr

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
setup.py

Amd64 version
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: amd64 version

---

hm_pyhelper/miner_param.py
setup.py

add x86_64 handling
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: add x86_64 handling

---

hm_pyhelper/hardware_definitions.py
setup.py

Changed aarch64 CPU architectures to arm64 as they are incompatible with miner images

Changed aarch64 CPU architectures to arm64 as they are incompatible

---

hm_pyhelper/hardware_definitions.py
setup.py

Add midas
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: initial addition of midas

---

hm_pyhelper/hardware_definitions.py
setup.py

midas reset pin is actually 17
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: fix midas reset pin

---

hm_pyhelper/hardware_definitions.py
setup.py

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Fix Sensecap name

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
setup.py

Fix pypi production build
**Issue**
- Link:
- Summary:
**How**
**References**
Closes: #240 
**Checklist**

fix: pypi production build

---

requirements.txt
setup.py
test-requirements.txt

Added grpcio back with correct version

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Fix update

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
setup.py

Update gateway-mfr-rs to latest release v0.4.2
Ref https://github.com/helium/gateway-mfr-rs/releases/tag/v0.4.2

gateway-mfr-rs: Update to latest release v0.4.2

---

hm_pyhelper/gateway_grpc/client.py
hm_pyhelper/tests/test_gateway_grpc.py
setup.py

**[Issue](https://nebraltd.atlassian.net/browse/NEBD-105)**
- Link: https://nebraltd.atlassian.net/browse/NEBD-105
- Summary:
**How**
**References**
**Checklist**

fix: incorporate proto changes #NEBD-105

---

hm_pyhelper/gateway_grpc/client.py
setup.py

**[Issue](https://nebraltd.atlassian.net/browse/NEBD-105)**
- Link: https://nebraltd.atlassian.net/browse/NEBD-105
- Summary:
**How**
**References**
**Checklist**

fix: base58 decoding fix #NEBD-105

---

hm_pyhelper/gateway_grpc/exceptions.py
hm_pyhelper/miner_param.py
setup.py

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

No longer throw exception when fetching Mac addresses

---

setup.py

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Bump version to 0.14.10 in setup.py

---

pyproject.toml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Bump version to 0.14.12

---

hm_pyhelper/hardware_definitions.py

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Add hardware definition for Bobcat PX30

---

hm_pyhelper/hardware_definitions.py
pyproject.toml

Add ram and bump version
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: add ram and bump version

---

hm_pyhelper/sbc.py
pyproject.toml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Add Rob's RockPi Dev Fleet for Commercial Fleets

---

hm_pyhelper/sbc.py
pyproject.toml

add check for nebra fleets
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: add check for nebra fleets

---

hm_pyhelper/sbc.py
pyproject.toml

Fix logic
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Fix Nebra fleet check

---

hm_pyhelper/sbc.py
hm_pyhelper/tests/test_sbc.py
pyproject.toml

Closes: #272
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

sbc: add test cases

---

hm_pyhelper/hardware_definitions.py
hm_pyhelper/sbc.py
hm_pyhelper/tests/test_hardware_definitions.py
pyproject.toml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

bobcat: add is_bobcat check

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
pyproject.toml

Update gateway-mfr-rs to latest release v0.5.0
Ref https://github.com/helium/gateway-mfr-rs/releases/tag/v0.5.0

gateway-mfr-rs: Update to latest release v0.5.0

---

hm_pyhelper/hardware_definitions.py
hm_pyhelper/sbc.py
hm_pyhelper/tests/test_hardware_definitions.py
pyproject.toml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Add support for Bobcat RK3566

---

.github/workflows/publish-to-pypi-test.yml
.github/workflows/publish-to-pypi.yml
pyproject.toml

Update gateway-mfr-rs to latest release v0.5.4
Ref https://github.com/helium/gateway-mfr-rs/releases/tag/v0.5.4

gateway-mfr-rs: Update to latest release v0.5.4

---

hm_pyhelper/hardware_definitions.py
pyproject.toml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Linxdot rk3566
